
# https://synthetichealth.github.io/synthea/
data_directory: data/synthea_sample_data_csv_apr2020

patients:
  csv_file: patients.csv

ehr_tables:  
  conditions:
    csv_file: conditions.csv
    features: ['START', 'STOP', 'DESCRIPTION']

  medications:
    csv_file: medications.csv
    features: ['START', 'STOP', 'DESCRIPTION', 'REASONDESCRIPTION']

  encounters:
    csv_file: encounters.csv
    features: ['START', 'STOP', 'DESCRIPTION', 'REASONDESCRIPTION']

  procedures:
    csv_file: procedures.csv
    features: ['DATE', 'DESCRIPTION', 'REASONDESCRIPTION']

  observations:
    csv_file: observations.csv
    features: ['DATE', 'DESCRIPTION', 'VALUE', 'UNITS']
  
  careplans:
    csv_file: careplans.csv
    features: ['START', 'STOP', 'DESCRIPTION', 'REASONDESCRIPTION']
  
  immunizations:
    csv_file: immunizations.csv
    features: ['DATE', 'DESCRIPTION']
  
  allergies:
    csv_file: allergies.csv
    features: ['START', 'STOP', 'DESCRIPTION']
  
  devices:
    csv_file: devices.csv
    features: ['START', 'STOP', 'DESCRIPTION']
  
  imaging_studies:
    csv_file: imaging_studies.csv
    features: ['DATE', 'BODYSITE_DESCRIPTION', 'MODALITY_DESCRIPTION', SOP_DESCRIPTION]